spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classBooking
    username: classDev
    password: p422wordDev
    driver-class-name: org.postgresql.Driver
logging:
  file:
    name: ./log/class-booking-api.log
    max-history: 10
application:
  security:
    jwt:
      secret-key: D3EA54FFD9B3CC700FA31C837709B8FD33831EC6F81A3A644293D51B0E051F22
      expiration: 900000
      refresh-token:
        expiration: 1800000
springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
server:
  port: 8080
api:
  version: v1.0

