spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 2000
      pool-name: MyHikariCP
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
logging:
  file:
    name: ./log/mediearth-t2k.log
    max-history: 10
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000
      refresh-token:
        expiration: 604800000
swagger:
  username: ENC(95ubgY4i8TX5mc5j7VcEcw==)
  password: ENC(dmN45z3Bry36AolSFAfANyJbYhgevXf3)
springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
server:
  port: 8091

